package biomolecules

enum class AminoAcid(override val symbol: Char, val mass: Double) : Monomer {
    Alanine('A', 071.03711),
    Cysteine('C', 103.00919),
    AsparticAcid('D', 115.02694),
    GlutamicAcid('E', 129.04259),
    Phenylalanine('F', 147.06841),
    Glycine('G', 057.02146),
    Histidine('H', 137.05891),
    Isoleucine('I', 113.08406),
    Lysine('K', 128.09496),
    Leucine('L', 113.08406),
    Methionine('M', 131.04049),
    Asparagine('N', 114.04293),
    Proline('P', 097.05276),
    Glutamine('Q', 128.05858),
    Arginine('R', 156.10111),
    Serine('S', 087.03203),
    Threonine('T', 101.04768),
    Valine('V', 099.06841),
    Tryptophan('W', 186.07931),
    Tyrosine('Y', 163.06333)
}

internal val codons = mapOf(
    listOf(Uracil, Uracil, Uracil) to AminoAcid.Phenylalanine,
    listOf(Cytosine, Uracil, Uracil) to AminoAcid.Leucine,
    listOf(Adenine, Uracil, Uracil) to AminoAcid.Isoleucine,
    listOf(Guanine, Uracil, Uracil) to AminoAcid.Valine,
    listOf(Uracil, Uracil, Cytosine) to AminoAcid.Phenylalanine,
    listOf(Cytosine, Uracil, Cytosine) to AminoAcid.Leucine,
    listOf(Adenine, Uracil, Cytosine) to AminoAcid.Isoleucine,
    listOf(Guanine, Uracil, Cytosine) to AminoAcid.Valine,
    listOf(Uracil, Uracil, Adenine) to AminoAcid.Leucine,
    listOf(Cytosine, Uracil, Adenine) to AminoAcid.Leucine,
    listOf(Adenine, Uracil, Adenine) to AminoAcid.Isoleucine,
    listOf(Guanine, Uracil, Adenine) to AminoAcid.Valine,
    listOf(Uracil, Uracil, Guanine) to AminoAcid.Leucine,
    listOf(Cytosine, Uracil, Guanine) to AminoAcid.Leucine,
    listOf(Guanine, Uracil, Guanine) to AminoAcid.Valine,
    listOf(Uracil, Cytosine, Uracil) to AminoAcid.Serine,
    listOf(Cytosine, Cytosine, Uracil) to AminoAcid.Proline,
    listOf(Adenine, Cytosine, Uracil) to AminoAcid.Threonine,
    listOf(Guanine, Cytosine, Uracil) to AminoAcid.Alanine,
    listOf(Uracil, Cytosine, Cytosine) to AminoAcid.Serine,
    listOf(Cytosine, Cytosine, Cytosine) to AminoAcid.Proline,
    listOf(Adenine, Cytosine, Cytosine) to AminoAcid.Threonine,
    listOf(Guanine, Cytosine, Cytosine) to AminoAcid.Alanine,
    listOf(Uracil, Cytosine, Adenine) to AminoAcid.Serine,
    listOf(Cytosine, Cytosine, Adenine) to AminoAcid.Proline,
    listOf(Adenine, Cytosine, Adenine) to AminoAcid.Threonine,
    listOf(Guanine, Cytosine, Adenine) to AminoAcid.Alanine,
    listOf(Uracil, Cytosine, Guanine) to AminoAcid.Serine,
    listOf(Cytosine, Cytosine, Guanine) to AminoAcid.Proline,
    listOf(Adenine, Cytosine, Guanine) to AminoAcid.Threonine,
    listOf(Guanine, Cytosine, Guanine) to AminoAcid.Alanine,
    listOf(Uracil, Adenine, Uracil) to AminoAcid.Tyrosine,
    listOf(Cytosine, Adenine, Uracil) to AminoAcid.Histidine,
    listOf(Adenine, Adenine, Uracil) to AminoAcid.Asparagine,
    listOf(Guanine, Adenine, Uracil) to AminoAcid.AsparticAcid,
    listOf(Uracil, Adenine, Cytosine) to AminoAcid.Tyrosine,
    listOf(Cytosine, Adenine, Cytosine) to AminoAcid.Histidine,
    listOf(Adenine, Adenine, Cytosine) to AminoAcid.Asparagine,
    listOf(Guanine, Adenine, Cytosine) to AminoAcid.AsparticAcid,
    listOf(Cytosine, Adenine, Adenine) to AminoAcid.Glutamine,
    listOf(Adenine, Adenine, Adenine) to AminoAcid.Lysine,
    listOf(Guanine, Adenine, Adenine) to AminoAcid.GlutamicAcid,
    listOf(Cytosine, Adenine, Guanine) to AminoAcid.Glutamine,
    listOf(Adenine, Adenine, Guanine) to AminoAcid.Lysine,
    listOf(Guanine, Adenine, Guanine) to AminoAcid.GlutamicAcid,
    listOf(Uracil, Guanine, Uracil) to AminoAcid.Cysteine,
    listOf(Cytosine, Guanine, Uracil) to AminoAcid.Arginine,
    listOf(Adenine, Guanine, Uracil) to AminoAcid.Serine,
    listOf(Guanine, Guanine, Uracil) to AminoAcid.Glycine,
    listOf(Uracil, Guanine, Cytosine) to AminoAcid.Cysteine,
    listOf(Cytosine, Guanine, Cytosine) to AminoAcid.Arginine,
    listOf(Adenine, Guanine, Cytosine) to AminoAcid.Serine,
    listOf(Guanine, Guanine, Cytosine) to AminoAcid.Glycine,
    listOf(Cytosine, Guanine, Adenine) to AminoAcid.Arginine,
    listOf(Adenine, Guanine, Adenine) to AminoAcid.Arginine,
    listOf(Guanine, Guanine, Adenine) to AminoAcid.Glycine,
    listOf(Uracil, Guanine, Guanine) to AminoAcid.Tryptophan,
    listOf(Cytosine, Guanine, Guanine) to AminoAcid.Arginine,
    listOf(Adenine, Guanine, Guanine) to AminoAcid.Arginine,
    listOf(Guanine, Guanine, Guanine) to AminoAcid.Glycine,
    listOf(Adenine, Uracil, Guanine) to AminoAcid.Methionine
)
